//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace IJunior.TypedScenes
{
    using UnityEngine.SceneManagement;
    
    
    public class Game : TypedScene
    {
        
        private const string GUID = "45b7489725de7634ba4d344ac18a3c17";
        
        public static void Load(bool argument, LoadSceneMode loadSceneMode = LoadSceneMode.Single)
        {
            LoadScene(GUID, loadSceneMode, argument);
        }
    }
}
